# -*- coding: utf-8 -*-
"""GSE_289218_geodataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMqZSvKAU5bWKyA2Ll4Kp_WUx7xHMIWo
"""

!apt-get install -y r-base

!apt-get update -qq
!apt-get install -y r-base
!pip install rpy2

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython

# Commented out IPython magic to ensure Python compatibility.
# %%R
# R.version.string

# Commented out IPython magic to ensure Python compatibility.
# %%R
# install.packages(c("ggplot2","ggrepel","readr"))

!pip install pandas matplotlib seaborn adjustText

import pandas as pd

deg72 = pd.read_csv("72hr_vs_Control.csv")
deg2wk = pd.read_csv("2wk_vs_Control.csv")

import os
os.listdir()

deg72.shape

"""# **Differntially expressed genes -  Control vs Test**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import umap
!pip install gseapy
import gseapy as gp
!pip install adjustText
from adjustText import adjust_text
import warnings
warnings.filterwarnings('ignore')

df_2wk  = pd.read_csv('/2wk_vs_Control.csv',  index_col=0)
df_72hr = pd.read_csv('/72hr_vs_Control.csv', index_col=0)

for df, label in [(df_2wk, '2wk'), (df_72hr, '72hr')]:
    df.rename(columns={
        'avg_log2FC': 'log2FC',
        'p_val':      'pval',
        'p_val_adj':  'padj'
    }, inplace=True)

df_2wk['group']  = '2wk'
df_72hr['group'] = '72hr'

FC_THRESH  = 1.0   # |log2FC| cutoff
ADJ_THRESH = 0.05  # adjusted p-value cutoff

def classify(df):
    """Add significance category column."""
    conds = [
        (df['padj'] < ADJ_THRESH) & (df['log2FC'] >  FC_THRESH),
        (df['padj'] < ADJ_THRESH) & (df['log2FC'] < -FC_THRESH),
    ]
    choices = ['Up Regulated', 'Down Regulated']
    df['sig'] = np.select(conds, choices, default='Not significant')
    return df

df_2wk  = classify(df_2wk)
df_72hr = classify(df_72hr)

palette = {'Up Regulated': '#E63946', 'Down Regulated': '#457B9D', 'Not significant': '#A8DADC'}

print("2wk  DEGs:", df_2wk['sig'].value_counts().to_dict())
print("72hr DEGs:", df_72hr['sig'].value_counts().to_dict())

"""# **Volcano plots - Control vs test**"""

def volcano_plot(ax, df, title, n_labels=15):
    df = df.copy()
    df['-log10padj'] = -np.log10(df['padj'].replace(0, 1e-300))
    for cat, color in palette.items():
        sub = df[df['sig'] == cat]
        ax.scatter(sub['log2FC'], sub['-log10padj'],
                   c=color, s=8, alpha=0.7, label=cat, rasterized=True)

    top = df[df['sig'] != 'Not significant'].nlargest(n_labels, '-log10padj')
    texts = [ax.text(row['log2FC'], row['-log10padj'], idx,
                     fontsize=6, fontweight='bold')
             for idx, row in top.iterrows()]
    adjust_text(texts, ax=ax, arrowprops=dict(arrowstyle='-', color='grey', lw=0.5))

    ax.set_xlabel('log₂ Fold Change', fontsize=11)
    ax.set_ylabel('-log₁₀ (adj. p-value)', fontsize=11)
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.legend(fontsize=9, markerscale=2)


fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=False)
volcano_plot(axes[0], df_2wk,  '2-Week vs Control')
volcano_plot(axes[1], df_72hr, '72-Hour vs Control')


all_fc = pd.concat([df_2wk['log2FC'], df_72hr['log2FC']])
max_fc = max(abs(all_fc.min()), abs(all_fc.max()))
for ax in axes:
    ax.set_xlim(-max_fc - 0.5, max_fc + 0.5)
    ax.set_xticks(range(int(-max_fc) - 1, int(max_fc) + 2))

plt.suptitle('Volcano Plots — GSE289218', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('volcano_plots.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: volcano_plots.png")

"""# **MA Plot - Control vs Test**"""

def ma_plot(ax, df, title):
    # A = average expression approximated from pct.1 and pct.2
    df = df.copy()
    df['A'] = (df['pct.1'] + df['pct.2']) / 2

    for cat, color in palette.items():
        sub = df[df['sig'] == cat]
        ax.scatter(sub['A'], sub['log2FC'],
                   c=color, s=8, alpha=0.7, label=cat, rasterized=True)

    ax.axhline( FC_THRESH,  color='grey', lw=0.8, ls='--')
    ax.axhline(-FC_THRESH,  color='grey', lw=0.8, ls='--')
    ax.axhline(0, color='black', lw=0.6)
    ax.set_xlabel('Average Detection Rate (A)', fontsize=11)
    ax.set_ylabel('log₂ Fold Change (M)', fontsize=11)
    ax.set_title(title, fontsize=13, fontweight='bold')
    ax.legend(fontsize=9, markerscale=2)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
ma_plot(axes[0], df_2wk,  'MA Plot — 2-Week vs Control')
ma_plot(axes[1], df_72hr, 'MA Plot — 72-Hour vs Control')
plt.suptitle('MA Plots — GSE289218', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('ma_plots.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: ma_plots.png")

"""# **Principal Component Analysis plots**"""

df_2wk_pca  = df_2wk[['log2FC','pct.1','pct.2']].copy()
df_72hr_pca = df_72hr[['log2FC','pct.1','pct.2']].copy()

df_2wk_pca['condition']  = '2wk'
df_72hr_pca['condition'] = '72hr'
df_2wk_pca['sig']  = df_2wk['sig']
df_72hr_pca['sig'] = df_72hr['sig']

combined = pd.concat([df_2wk_pca, df_72hr_pca]).dropna()
print("Combined shape for PCA:", combined.shape)
X      = combined[['log2FC','pct.1','pct.2']].values
labels = combined['sig'].values
cond   = combined['condition'].values

X_scaled = StandardScaler().fit_transform(X)

pca    = PCA(n_components=2, random_state=42)
coords = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame({
    'PC1': coords[:,0],
    'PC2': coords[:,1],
    'sig': labels,
    'condition': cond
})

print(pca_df['sig'].value_counts())
fig, ax = plt.subplots(figsize=(8, 7))
for cat, color in palette.items():
    sub = pca_df[pca_df['sig'] == cat]
    ax.scatter(sub['PC1'], sub['PC2'], c=color, s=10,
               alpha=0.7, label=cat, rasterized=True)

ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)", fontsize=12)
ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)", fontsize=12)
ax.set_title('PCA — All Genes (2wk & 72hr vs Control)', fontsize=13, fontweight='bold')
ax.legend(fontsize=10, markerscale=2)
plt.tight_layout()
plt.savefig('pca_plot.png', dpi=150, bbox_inches='tight')
plt.show()

"""# **UMAP Plot**"""

reducer = umap.UMAP(n_components=2, random_state=42, n_neighbors=30, min_dist=0.3)
umap_coords = reducer.fit_transform(X_scaled)
umap_df = pd.DataFrame({
    'UMAP1': umap_coords[:,0],
    'UMAP2': umap_coords[:,1],
    'sig':       labels,
    'condition': cond
})

fig, ax = plt.subplots(figsize=(8, 7))
for cat, color in palette.items():
    sub = umap_df[umap_df['sig'] == cat]
    ax.scatter(sub['UMAP1'], sub['UMAP2'], c=color, s=10,
               alpha=0.7, label=cat, rasterized=True)

ax.set_xlabel('UMAP 1', fontsize=12)
ax.set_ylabel('UMAP 2', fontsize=12)
ax.set_title('UMAP — All Genes (2wk & 72hr vs Control)', fontsize=13, fontweight='bold')
ax.legend(fontsize=10, markerscale=2)
plt.tight_layout()
plt.savefig('umap_plot.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: umap_plot.png")

"""# **CELL BASED ANALYSIS**"""

# GSE295097
# Microglia & Astrocytes | Radiation 72hr & 2wk vs Control

!pip install pandas numpy matplotlib seaborn scikit-learn umap-learn adjustText gseapy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import umap
import gseapy as gp
!pip install gseapy
from adjustText import adjust_text
!pip install adjustText
import warnings
warnings.filterwarnings('ignore')

!pip install gseapy

plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor':   'white',
    'axes.spines.top':  False,
    'axes.spines.right':False,
    'font.family':      'sans-serif',
    'axes.grid':        False
})

meta      = pd.read_csv('metadata.csv',    index_col=0)
umap_df   = pd.read_csv('umap_coords.csv', index_col=0)
pca_df    = pd.read_csv('pca_coords.csv',  index_col=0)

deg_files = {
    ('Microglia',  '72hr'): pd.read_csv('DEG_Microglia_72hr_vs_Control.csv',  index_col=0),
    ('Microglia',  '2wk'):  pd.read_csv('DEG_Microglia_2wk_vs_Control.csv',   index_col=0),
    ('Astrocyte',  '72hr'): pd.read_csv('DEG_Astrocyte_72hr_vs_Control.csv',  index_col=0),
    ('Astrocyte',  '2wk'):  pd.read_csv('DEG_Astrocyte_2wk_vs_Control.csv',   index_col=0),
}


for key in deg_files:
    deg_files[key].rename(columns={
        'avg_log2FC': 'log2FC',
        'p_val':      'pval',
        'p_val_adj':  'padj'
    }, inplace=True)


common_cells = meta.index.intersection(umap_df.index).intersection(pca_df.index)
meta    = meta.loc[common_cells]
umap_df = umap_df.loc[common_cells]
pca_df  = pca_df.loc[common_cells]


meta['umap_1'] = umap_df['umap_1']
meta['umap_2'] = umap_df['umap_2']
meta['PC1']    = pca_df.iloc[:, 0]
meta['PC2']    = pca_df.iloc[:, 1]

print(f"Total cells: {len(meta)}")
print(meta['cell_type'].value_counts())
print(meta['Condition'].value_counts())


FC_THRESH  = 0.5
ADJ_THRESH = 0.05

def classify(df):
    conds   = [
        (df['padj'] < ADJ_THRESH) & (df['log2FC'] >  FC_THRESH),
        (df['padj'] < ADJ_THRESH) & (df['log2FC'] < -FC_THRESH),
    ]
    df['sig'] = np.select(conds, ['Up', 'Down'], default='NS')
    return df

for key in deg_files:
    deg_files[key] = classify(deg_files[key])
    ct, tp = key
    print(f"{ct} {tp}: {deg_files[key]['sig'].value_counts().to_dict()}")


cell_palette = {
    'Astrocyte': '#E63946',
    'Microglia': '#457B9D',
    'Other':     '#CCCCCC'
}
cond_palette = {
    'Control':        '#2D6A4F',
    'Radiation_72hr': '#F4A261',
    'Radiation_2wk':  '#9B2226'
}
sig_palette = {'Up': '#E63946', 'Down': '#457B9D', 'NS': '#D3D3D3'}

# ════════════════════════════════════════════════════════════
# UMAP: Cell Type Annotation
# ════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# Panel A: by cell type
for ct, color in cell_palette.items():
    sub = meta[meta['cell_type'] == ct]
    axes[0].scatter(sub['umap_1'], sub['umap_2'],
                    c=color, s=1.5, alpha=0.6,
                    label=f"{ct} (n={len(sub):,})", rasterized=True)
axes[0].set_xlabel('UMAP 1', fontsize=12)
axes[0].set_ylabel('UMAP 2', fontsize=12)
axes[0].set_title('UMAP — Cell Type Annotation', fontsize=13, fontweight='bold')
axes[0].legend(fontsize=9, markerscale=5, frameon=True,
               loc='lower left', title='Cell Type')

# Panel B: by condition
for cond, color in cond_palette.items():
    sub = meta[meta['Condition'] == cond]
    axes[1].scatter(sub['umap_1'], sub['umap_2'],
                    c=color, s=1.5, alpha=0.5,
                    label=f"{cond} (n={len(sub):,})", rasterized=True)
axes[1].set_xlabel('UMAP 1', fontsize=12)
axes[1].set_ylabel('UMAP 2', fontsize=12)
axes[1].set_title('UMAP — Condition', fontsize=13, fontweight='bold')
axes[1].legend(fontsize=9, markerscale=5, frameon=True,
               loc='lower left', title='Condition')

plt.suptitle('Single-Cell UMAP — GSE295097 (Radiation Model)',
             fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('UMAP_CellType_Condition.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: UMAP_CellType_Condition.png")

# ════════════════════════════════════════════════════════════
# UMAP: Split by Cell Type × Condition
# ════════════════════════════════════════════════════════════
cell_types = ['Astrocyte', 'Microglia']
conditions = ['Control', 'Radiation_72hr', 'Radiation_2wk']

fig, axes = plt.subplots(2, 3, figsize=(18, 11))

for i, ct in enumerate(cell_types):
    for j, cond in enumerate(conditions):
        ax = axes[i][j]

        ax.scatter(meta['umap_1'], meta['umap_2'],
                   c='#EBEBEB', s=0.5, alpha=0.3, rasterized=True)

        sub = meta[(meta['cell_type'] == ct) & (meta['Condition'] == cond)]
        ax.scatter(sub['umap_1'], sub['umap_2'],
                   c=cell_palette[ct], s=2, alpha=0.8, rasterized=True)
        ax.set_title(f'{ct}\n{cond} (n={len(sub):,})',
                     fontsize=10, fontweight='bold')
        ax.set_xlabel('UMAP 1', fontsize=8)
        ax.set_ylabel('UMAP 2', fontsize=8)
        ax.tick_params(labelsize=7)

plt.suptitle('UMAP — Cell Type × Condition Split\nGSE295097',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('UMAP_Split_CellType_Condition.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: UMAP_Split_CellType_Condition.png")

# ════════════════════════════════════════════════════════════
# PCA: Cell-Level (Seurat PCA coordinates)
# ════════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

# Panel A: by cell type
for ct, color in cell_palette.items():
    sub = meta[meta['cell_type'] == ct]
    axes[0].scatter(sub['PC1'], sub['PC2'],
                    c=color, s=1.5, alpha=0.5,
                    label=f"{ct} (n={len(sub):,})", rasterized=True)
axes[0].set_xlabel('PC1', fontsize=12)
axes[0].set_ylabel('PC2', fontsize=12)
axes[0].set_title('PCA — Cell Type', fontsize=13, fontweight='bold')
axes[0].legend(fontsize=9, markerscale=5, frameon=True, title='Cell Type')

# Panel B: by condition
for cond, color in cond_palette.items():
    sub = meta[meta['Condition'] == cond]
    axes[1].scatter(sub['PC1'], sub['PC2'],
                    c=color, s=1.5, alpha=0.4,
                    label=cond, rasterized=True)
axes[1].set_xlabel('PC1', fontsize=12)
axes[1].set_ylabel('PC2', fontsize=12)
axes[1].set_title('PCA — Condition', fontsize=13, fontweight='bold')
axes[1].legend(fontsize=9, markerscale=5, frameon=True, title='Condition')

plt.suptitle('PCA (Seurat) — GSE295097', fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('PCA_CellType_Condition.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: PCA_CellType_Condition.png")

# ════════════════════════════════════════════════════════════
# PCA: Cell-Type Subset Only (Microglia + Astrocyte)
# ════════════════════════════════════════════════════════════
meta_sub = meta[meta['cell_type'].isin(['Microglia', 'Astrocyte'])].copy()

fig, axes = plt.subplots(1, 2, figsize=(16, 7))

for ct, color in cell_palette.items():
    if ct == 'Other': continue
    sub = meta_sub[meta_sub['cell_type'] == ct]
    axes[0].scatter(sub['PC1'], sub['PC2'], c=color, s=3,
                    alpha=0.6, label=f"{ct} (n={len(sub):,})", rasterized=True)
axes[0].set_xlabel('PC1', fontsize=12)
axes[0].set_ylabel('PC2', fontsize=12)
axes[0].set_title('PCA — Microglia & Astrocytes Only\n(Cell Type)',
                  fontsize=12, fontweight='bold')
axes[0].legend(fontsize=10, markerscale=3, frameon=True)

for cond, color in cond_palette.items():
    sub = meta_sub[meta_sub['Condition'] == cond]
    axes[1].scatter(sub['PC1'], sub['PC2'], c=color, s=3,
                    alpha=0.5, label=cond, rasterized=True)
axes[1].set_xlabel('PC1', fontsize=12)
axes[1].set_ylabel('PC2', fontsize=12)
axes[1].set_title('PCA — Microglia & Astrocytes Only\n(Condition)',
                  fontsize=12, fontweight='bold')
axes[1].legend(fontsize=10, markerscale=3, frameon=True)

plt.suptitle('PCA — Glial Cells Only (GSE295097)',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('PCA_GlialCells_Only.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: PCA_GlialCells_Only.png")

# ════════════════════════════════════════════════════════════
# VOLCANO PLOTS: Cell-Type Specific
# ════════════════════════════════════════════════════════════
def volcano_plot(ax, df, title, n_labels=15):
    df = df.copy()
    df['-log10padj'] = -np.log10(df['padj'].replace(0, 1e-300))
    for cat, color in sig_palette.items():
        sub = df[df['sig'] == cat]
        ax.scatter(sub['log2FC'], sub['-log10padj'],
                   c=color, s=8, alpha=0.7, label=cat, rasterized=True)
    top = df[df['sig'] != 'NS'].nlargest(n_labels, '-log10padj')
    texts = [ax.text(row['log2FC'], row['-log10padj'], idx,
                     fontsize=6, fontweight='bold')
             for idx, row in top.iterrows()]
    adjust_text(texts, ax=ax,
                arrowprops=dict(arrowstyle='-', color='grey', lw=0.5))
    ax.axhline(-np.log10(ADJ_THRESH), color='grey', lw=0.8, ls='--')
    ax.axvline( FC_THRESH, color='grey', lw=0.8, ls='--')
    ax.axvline(-FC_THRESH, color='grey', lw=0.8, ls='--')
    ax.set_xlabel('log₂ Fold Change', fontsize=11)
    ax.set_ylabel('-log₁₀ (adj. p-value)', fontsize=11)
    ax.set_title(title, fontsize=11, fontweight='bold')
    ax.legend(fontsize=8, markerscale=2)

fig, axes = plt.subplots(2, 2, figsize=(16, 14))
plot_order = [
    (('Microglia', '72hr'), axes[0][0], 'Microglia — 72hr vs Control'),
    (('Microglia', '2wk'),  axes[0][1], 'Microglia — 2wk vs Control'),
    (('Astrocyte', '72hr'), axes[1][0], 'Astrocyte — 72hr vs Control'),
    (('Astrocyte', '2wk'),  axes[1][1], 'Astrocyte — 2wk vs Control'),
]
for (key, ax, title) in plot_order:
    volcano_plot(ax, deg_files[key], title)

# Sync x-axis
all_fc = pd.concat([df['log2FC'] for df in deg_files.values()])
max_fc = max(abs(all_fc.min()), abs(all_fc.max()))
for row in axes:
    for ax in row:
        ax.set_xlim(-max_fc - 0.5, max_fc + 0.5)
        ax.set_xticks(range(int(-max_fc)-1, int(max_fc)+2))

plt.suptitle('Volcano Plots — Cell-Type Specific DEGs\nGSE295097 Radiation Model',
             fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('Volcano_CellType_Specific.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: Volcano_CellType_Specific.png")

# ════════════════════════════════════════════════════════════
# HEATMAP: Top DEGs per Cell Type
# ════════════════════════════════════════════════════════════
def get_top_degs(df, n=30):
    up   = df[df['sig'] == 'Up'].nlargest(n//2,   'log2FC')
    down = df[df['sig'] == 'Down'].nsmallest(n//2, 'log2FC')
    return pd.concat([up, down])

fig, axes = plt.subplots(1, 2, figsize=(14, 12))

for ax, ct in zip(axes, ['Microglia', 'Astrocyte']):
    df_72  = deg_files[(ct, '72hr')]
    df_2wk = deg_files[(ct, '2wk')]
    top_genes = list(set(
        get_top_degs(df_72).index.tolist() +
        get_top_degs(df_2wk).index.tolist()
    ))
    hm = pd.DataFrame({
        '72hr': df_72.reindex(top_genes)['log2FC'],
        '2wk':  df_2wk.reindex(top_genes)['log2FC']
    }).dropna()
    hm = hm.iloc[np.argsort(hm.mean(axis=1))]

    sns.heatmap(hm, cmap='RdBu_r', center=0, ax=ax,
                linewidths=0.2, yticklabels=True,
                cbar_kws={'label': 'log₂FC', 'shrink': 0.6})
    ax.set_title(f'{ct}\nTop DEGs', fontsize=12, fontweight='bold')
    ax.set_xticklabels(['72hr vs Ctrl', '2wk vs Ctrl'], fontsize=10)
    ax.set_yticklabels(ax.get_yticklabels(), fontsize=6)

plt.suptitle('DEG Heatmap — Microglia & Astrocytes\nGSE295097 Radiation Model',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('Heatmap_CellType_DEGs.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: Heatmap_CellType_DEGs.png")

"""# **Pathway Enrichment Analysis**"""

# ════════════════════════════════════════════════════════════
# NEUROINFLAMMATORY PATHWAY ENRICHMENT
# ════════════════════════════════════════════════════════════

GENE_SETS = [
    'GO_Biological_Process_2023',
    'KEGG_2021_Human',
    'Reactome_2022'
]

NEURO_KEYWORDS = [
    'inflamm', 'microglia', 'astrocyte', 'neuroinflam', 'cytokine',
    'nf-kb', 'nfkb', 'tnf', 'interleukin', 'chemokine', 'immune',
    'complement', 'glial', 'oxidative', 'apoptosis', 'autophagy',
    'toll-like', 'tlr', 'jak', 'stat', 'mapk', 'reactive oxygen',
    'interferon', 'macrophage', 'phagocyt', 'synaptic', 'neurotox'
]

def is_neuroinflammatory(term):
    term_lower = term.lower()
    return any(kw in term_lower for kw in NEURO_KEYWORDS)

def run_neuro_enrichment(df, cell_type, timepoint, direction='Up', top_n=25):
    gene_list = df[df['sig'] == direction].index.tolist()
    if len(gene_list) < 5:
        print(f"  Skipping {cell_type} {timepoint} {direction}: too few genes ({len(gene_list)})")
        return None

    print(f"  Running: {cell_type} | {timepoint} | {direction} | n={len(gene_list)}")
    try:
        enr = gp.enrichr(
            gene_list=gene_list,
            gene_sets=GENE_SETS,
            organism='human',
            outdir=None
        )
        res = enr.results.copy()
        res = res[res['Adjusted P-value'] < 0.05]

        if res.empty:
            print(f"  No significant terms found.")
            return None


        neuro = res[res['Term'].apply(is_neuroinflammatory)]
        if neuro.empty:
            print(f"  No neuroinflammatory terms — showing all significant terms instead.")
            neuro = res

        neuro = neuro.nsmallest(top_n, 'Adjusted P-value').copy()
        neuro['-log10padj']  = -np.log10(neuro['Adjusted P-value'])
        neuro['Gene_count']  = neuro['Overlap'].apply(
            lambda x: int(x.split('/')[0]) if isinstance(x, str) else 0)
        neuro['Term_short']  = neuro['Term'].str[:60]
        neuro = neuro.sort_values('-log10padj', ascending=True)


        source_colors = {
            'GO_Biological_Process_2023': '#E63946',
            'KEGG_2021_Human':            '#457B9D',
            'Reactome_2022':              '#2D6A4F'
        }
        colors = neuro['Gene_Sets'].map(source_colors).fillna('#888888')

        fig, ax = plt.subplots(figsize=(11, max(5, len(neuro) * 0.38)))
        scatter = ax.scatter(
            neuro['-log10padj'],
            range(len(neuro)),
            c=neuro['-log10padj'],
            cmap='YlOrRd',
            s=neuro['Gene_count'] * 10,
            alpha=0.85,
            edgecolors='grey',
            linewidths=0.3
        )
        ax.set_yticks(range(len(neuro)))
        ax.set_yticklabels(neuro['Term_short'], fontsize=8)
        ax.set_xlabel('-log₁₀ (Adjusted P-value)', fontsize=11)
        ax.set_title(
            f'Neuroinflammatory Pathways\n{cell_type} | {timepoint} vs Control | '
            f'{direction}-regulated genes',
            fontsize=12, fontweight='bold'
        )
        cbar = plt.colorbar(scatter, ax=ax, shrink=0.5)
        cbar.set_label('-log₁₀ padj', fontsize=9)


        for s in [5, 15, 30]:
            ax.scatter([], [], s=s*10, c='grey', alpha=0.6, label=f'{s} genes')
        ax.legend(title='Gene count', fontsize=8, loc='lower right')


        patches = [mpatches.Patch(color=c, label=gs.split('_')[0])
                   for gs, c in source_colors.items()]
        ax.legend(handles=patches, title='Database', fontsize=8,
                  loc='upper left', frameon=True)

        plt.tight_layout()
        fname = f'Enrichment_{cell_type}_{timepoint}_{direction}.png'
        plt.savefig(fname, dpi=150, bbox_inches='tight')
        plt.show()
        print(f"  Saved: {fname}")
        return neuro

    except Exception as e:
        print(f"  Enrichment error: {e}")
        return None


print("\n── Neuroinflammatory Pathway Enrichment ──")
enrichment_results = {}
for (ct, tp), df in deg_files.items():
    for direction in ['Up', 'Down']:
        result = run_neuro_enrichment(df, ct, tp, direction)
        enrichment_results[(ct, tp, direction)] = result

print("\n── Saving Enrichment CSVs ──")

for (ct, tp, direction), result in enrichment_results.items():
    if result is not None:
        fname = f'Enrichment_{ct}_{tp}_{direction}.csv'

        save_cols = ['Term', 'Gene_Sets', 'Overlap', 'P-value',
                     'Adjusted P-value', 'Genes', '-log10padj', 'Gene_count']
        save_cols = [c for c in save_cols if c in result.columns]
        result[save_cols].to_csv(fname, index=False)
        print(f"  Saved: {fname}")
    else:
        print(f"  Skipped {ct} {tp} {direction} — no significant results")


from google.colab import files
import glob

csv_files = glob.glob('Enrichment_*.csv')
print(f"\nDownloading {len(csv_files)} CSV files...")
for f in csv_files:
    files.download(f)
    print(f"  Downloaded: {f}")

for (ct, tp), df in deg_files.items():
    print(f"\n{ct} {tp}:")
    print(f"  Total genes: {len(df)}")
    print(f"  Sig counts: {df['sig'].value_counts().to_dict()}")
    print(f"  Sample Up genes: {df[df['sig']=='Up'].index[:5].tolist()}")
    print(f"  Sample Down genes: {df[df['sig']=='Down'].index[:5].tolist()}")

# CLEAN GENE LIST: Remove lncRNAs, pseudogenes, Ensembl IDs
def clean_gene_list(gene_list):
    cleaned = []
    for g in gene_list:

        if g.startswith('ENSG'): continue

        if 'LINC' in g: continue

        if g.endswith('-AS1') or g.endswith('-AS2'): continue
        if g.endswith('-IT1') or g.endswith('-IT2'): continue

        if '-PS' in g: continue

        if g.startswith('MT-'): continue

        cleaned.append(g)
    return cleaned


for (ct, tp), df in deg_files.items():
    up_raw   = df[df['sig'] == 'Up'].index.tolist()
    down_raw = df[df['sig'] == 'Down'].index.tolist()
    up_clean   = clean_gene_list(up_raw)
    down_clean = clean_gene_list(down_raw)
    print(f"{ct} {tp}: Up {len(up_raw)}→{len(up_clean)} | Down {len(down_raw)}→{len(down_clean)}")

# RERUN ENRICHMENT WITH CLEANED GENE LISTS
def run_enrichment_clean(df, cell_type, timepoint, direction='Up', top_n=25):
    raw_genes   = df[df['sig'] == direction].index.tolist()
    gene_list   = clean_gene_list(raw_genes)

    print(f"\n{cell_type} {timepoint} {direction}: {len(raw_genes)} raw → {len(gene_list)} clean")
    if len(gene_list) < 10:
        print(f"  Too few clean genes, skipping.")
        return None

    try:
        enr = gp.enrichr(
            gene_list=gene_list,
            gene_sets=[
                'GO_Biological_Process_2023',
                'KEGG_2021_Human',
                'Reactome_2022'
            ],
            organism='human',
            outdir=None
        )
        res = enr.results.copy()
        sig = res[res['Adjusted P-value'] < 0.05]

        print(f"  Total terms: {len(res)} | Significant: {len(sig)}")

        if sig.empty:

            sig = res[res['P-value'] < 0.01]
            print(f"  Fallback to p<0.01: {len(sig)} terms")

        if sig.empty:
            print(f"  No results found.")
            return None


        neuro = sig[sig['Term'].apply(is_neuroinflammatory)]
        if neuro.empty:
            print(f"  No neuro terms — using all significant terms")
            neuro = sig

        neuro = neuro.nsmallest(top_n, 'Adjusted P-value').copy()
        neuro['-log10padj'] = -np.log10(neuro['Adjusted P-value'].replace(0, 1e-300))
        neuro['Gene_count'] = neuro['Overlap'].apply(
            lambda x: int(x.split('/')[0]) if isinstance(x, str) else 0)
        neuro['Term_short'] = neuro['Term'].str[:60]
        neuro = neuro.sort_values('-log10padj', ascending=True)


        fig, ax = plt.subplots(figsize=(11, max(5, len(neuro) * 0.38)))
        scatter = ax.scatter(
            neuro['-log10padj'], range(len(neuro)),
            c=neuro['-log10padj'], cmap='YlOrRd',
            s=neuro['Gene_count'] * 10,
            alpha=0.85, edgecolors='grey', linewidths=0.3
        )
        ax.set_yticks(range(len(neuro)))
        ax.set_yticklabels(neuro['Term_short'], fontsize=8)
        ax.set_xlabel('-log₁₀ (Adjusted P-value)', fontsize=11)
        ax.set_title(
            f'Enriched Pathways — {cell_type} | {timepoint} vs Control | {direction}-regulated',
            fontsize=12, fontweight='bold'
        )
        cbar = plt.colorbar(scatter, ax=ax, shrink=0.5)
        cbar.set_label('-log₁₀ padj', fontsize=9)
        for s in [5, 15, 30]:
            ax.scatter([], [], s=s*10, c='grey', alpha=0.6, label=f'{s} genes')
        ax.legend(title='Gene count', fontsize=8, loc='lower right')
        plt.tight_layout()

        png_fname = f'Enrichment_{cell_type}_{timepoint}_{direction}.png'
        plt.savefig(png_fname, dpi=150, bbox_inches='tight')
        plt.show()


        csv_fname = f'Enrichment_{cell_type}_{timepoint}_{direction}.csv'
        save_cols = [c for c in ['Term','Gene_Sets','Overlap','P-value',
                                  'Adjusted P-value','Genes',
                                  '-log10padj','Gene_count'] if c in neuro.columns]
        neuro[save_cols].to_csv(csv_fname, index=False)
        print(f"  Saved: {png_fname} + {csv_fname}")
        return neuro

    except Exception as e:
        print(f"  Error: {e}")
        return None


enrichment_results = {}
for (ct, tp), df in deg_files.items():
    for direction in ['Up', 'Down']:
        result = run_enrichment_clean(df, ct, tp, direction)
        enrichment_results[(ct, tp, direction)] = result

"""# **Pathway enrichment Plot: Microglia vs Astrocyte**"""

# ════════════════════════════════════════════════════════════
# COMPARATIVE BUBBLE PLOT: Microglia vs Astrocyte
# ════════════════════════════════════════════════════════════
def compare_enrichment(ct1_res, ct2_res, ct1_name, ct2_name, timepoint):
    if ct1_res is None or ct2_res is None:
        print(f"  Skipping comparison — missing results for {timepoint}")
        return


    top_ct1 = set(ct1_res.nsmallest(15, 'Adjusted P-value')['Term_short'].tolist())
    top_ct2 = set(ct2_res.nsmallest(15, 'Adjusted P-value')['Term_short'].tolist())
    shared  = top_ct1.union(top_ct2)

    rows = []
    for term in shared:
        r1 = ct1_res[ct1_res['Term_short'] == term]
        r2 = ct2_res[ct2_res['Term_short'] == term]
        rows.append({
            'Term':       term,
            f'{ct1_name}_log10p': -np.log10(r1['Adjusted P-value'].values[0]) if len(r1) else 0,
            f'{ct2_name}_log10p': -np.log10(r2['Adjusted P-value'].values[0]) if len(r2) else 0,
        })

    comp = pd.DataFrame(rows).set_index('Term')
    comp = comp.sort_values(f'{ct1_name}_log10p', ascending=False).head(20)

    fig, ax = plt.subplots(figsize=(8, max(6, len(comp)*0.4)))
    x = np.arange(len(comp))
    w = 0.35
    ax.barh(x - w/2, comp[f'{ct1_name}_log10p'], w,
            color='#E63946', alpha=0.85, label=ct1_name)
    ax.barh(x + w/2, comp[f'{ct2_name}_log10p'], w,
            color='#457B9D', alpha=0.85, label=ct2_name)
    ax.set_yticks(x)
    ax.set_yticklabels(comp.index, fontsize=8)
    ax.set_xlabel('-log₁₀ (Adjusted P-value)', fontsize=11)
    ax.set_title(f'Neuroinflammatory Pathway Comparison\n{ct1_name} vs {ct2_name} | {timepoint}',
                 fontsize=12, fontweight='bold')
    ax.axvline(x=-np.log10(0.05), color='black', lw=0.8, ls='--', alpha=0.5)
    ax.legend(fontsize=10)
    plt.tight_layout()
    fname = f'Pathway_Comparison_{timepoint}.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"Saved: {fname}")


for tp in ['72hr', '2wk']:
    compare_enrichment(
        enrichment_results.get(('Microglia', tp, 'Up')),
        enrichment_results.get(('Astrocyte', tp, 'Up')),
        'Microglia', 'Astrocyte', tp
    )

"""# **Differentially Expressed Genes - between cell types**"""

# ════════════════════════════════════════════════════════════
# DEG OVERLAP: Venn diagram
# ════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

for ax, tp in zip(axes, ['72hr', '2wk']):
    micro_up   = set(deg_files[('Microglia', tp)][deg_files[('Microglia', tp)]['sig']=='Up'].index)
    micro_down = set(deg_files[('Microglia', tp)][deg_files[('Microglia', tp)]['sig']=='Down'].index)
    astro_up   = set(deg_files[('Astrocyte', tp)][deg_files[('Astrocyte', tp)]['sig']=='Up'].index)
    astro_down = set(deg_files[('Astrocyte', tp)][deg_files[('Astrocyte', tp)]['sig']=='Down'].index)

    categories = [
        'Microglia\nOnly Up',   'Shared\nUp',   'Astrocyte\nOnly Up',
        'Microglia\nOnly Down', 'Shared\nDown', 'Astrocyte\nOnly Down'
    ]
    values = [
        len(micro_up - astro_up),      len(micro_up & astro_up),   len(astro_up - micro_up),
        len(micro_down - astro_down),  len(micro_down & astro_down), len(astro_down - micro_down)
    ]
    colors = ['#457B9D','#9B2226','#E63946',
              '#A8DADC','#6D6875','#F4A261']

    bars = ax.bar(categories, values, color=colors, alpha=0.85, edgecolor='white', lw=1.2)
    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                str(val), ha='center', va='bottom', fontsize=9, fontweight='bold')
    ax.set_ylabel('Number of DEGs', fontsize=11)
    ax.set_title(f'DEG Overlap — {tp} vs Control\n(padj<{ADJ_THRESH}, |log2FC|>{FC_THRESH})',
                 fontsize=11, fontweight='bold')
    ax.tick_params(axis='x', labelsize=8)

plt.suptitle('Microglia vs Astrocyte DEG Overlap — GSE295097',
             fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('DEG_Overlap_Comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("Saved: DEG_Overlap_Comparison.png")

print("\n✅ All plots complete!")
print("\nFiles generated:")
files = [
    "UMAP_CellType_Condition.png",
    "UMAP_Split_CellType_Condition.png",
    "PCA_CellType_Condition.png",
    "PCA_GlialCells_Only.png",
    "Volcano_CellType_Specific.png",
    "Heatmap_CellType_DEGs.png",
    "Enrichment_*.png  (up to 8 files)",
    "Pathway_Comparison_72hr.png",
    "Pathway_Comparison_2wk.png",
    "DEG_Overlap_Comparison.png"
]
for f in files:
    print(f"  → {f}")